# Pour des références : http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

# MongoDB
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: monobloc

# Flickr API
flickr:
    groups: 16809958@N00, 55736978@N00, 949716@N25
    maxPicturesPerGroup: 10

# application and server logging
logging:
  level:
    root: WARN
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.web: WARN
    org.springframework.security: WARN
    fr.agaetis: DEBUG