# Pour des références : http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
app:
  name: Mediobot
  description: Service to serve medias for Monobot
  version: 1.0

# Embedded Server
server:
  port: 8080

#Swagger API
springfox:
  documentation:
    swagger:
      v2:
        path: /_api-docs

# Flickr API
flickr:
    groups: 16809958@N00, 55736978@N00, 949716@N25

# MongoDB
spring:
  data:
    mongodb:
      host: mongo-service
      port: 27017
      database: mediobot

# application and server logging
logging:
  level:
    root: WARN
    org.springframework.web: WARN
    org.springframework.security: WARN
    fr.agaetis: INFO