# Pour des références : http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

app:
    name: Mediobot
    description: Service to serve medias for Monobot
    version: O.0.snap
    api:
        key: changeme
        secret: changeme


# Embedded Server Configuration
server:
    port: 8080

#Swagger API
springfox:
    documentation:
        swagger:
            v2:
                path: /_api-docs

spring:
    # HTTP server config
    http:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
flickr:
    groups: 16809958@N00, 55736978@N00, 949716@N25

info:
    app:
        name: ${app.name}
        description: ${app.description}
        version: ${app.version}

# application and server logging
logging:
    level:
        root: WARN
        org.springframework.web: WARN
        org.springframework.security: WARN
        fr.agaetis: DEBUG